//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foundry.Triggerscript.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foundry.Triggerscript.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DictionaryOfInt32DictionaryOfInt32ScriptLogicPrototype&gt;
        ///  &lt;KeyValuePairOfInt32DictionaryOfInt32ScriptLogicPrototype&gt;
        ///    &lt;Key&gt;2&lt;/Key&gt;
        ///    &lt;Value&gt;
        ///      &lt;KeyValuePairOfInt32ScriptLogicPrototype&gt;
        ///        &lt;Key&gt;5&lt;/Key&gt;
        ///        &lt;Value&gt;
        ///          &lt;Name&gt;CanGetUnits&lt;/Name&gt;
        ///          &lt;Version&gt;5&lt;/Version&gt;
        ///          &lt;DBID&gt;2&lt;/DBID&gt;
        ///          &lt;Params&gt;
        ///            &lt;Param&gt;
        ///              &lt;Name&gt;Location&lt;/Name&gt;
        ///              &lt;ID&gt;1&lt;/ID&gt;
        ///              &lt;Optional&gt;true&lt;/Optio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string conditions {
            get {
                return ResourceManager.GetString("conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DictionaryOfInt32DictionaryOfInt32ScriptLogicPrototype&gt;
        ///  &lt;KeyValuePairOfInt32DictionaryOfInt32ScriptLogicPrototype&gt;
        ///    &lt;Key&gt;37&lt;/Key&gt;
        ///    &lt;Value&gt;
        ///      &lt;KeyValuePairOfInt32ScriptLogicPrototype&gt;
        ///        &lt;Key&gt;3&lt;/Key&gt;
        ///        &lt;Value&gt;
        ///          &lt;Name&gt;Kill&lt;/Name&gt;
        ///          &lt;Version&gt;3&lt;/Version&gt;
        ///          &lt;DBID&gt;37&lt;/DBID&gt;
        ///          &lt;Params&gt;
        ///            &lt;Param&gt;
        ///              &lt;Name&gt;Unit&lt;/Name&gt;
        ///              &lt;ID&gt;3&lt;/ID&gt;
        ///              &lt;Optional&gt;true&lt;/Optional&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string effects {
            get {
                return ResourceManager.GetString("effects", resourceCulture);
            }
        }
    }
}
