using System.Xml.Linq;

Dictionary<string, string> categories = new Dictionary<string, string>()
{
    {"AISquadAnalysisVar", "Page 1"},
            {"AISquadAnalysisComponentVar", "Page 1"},
            {"AnimTypeVar", "Page 1"},
            {"BidStateVar", "Page 1"},
            {"BidTypeVar", "Page 1"},
            {"BoolVar", "Page 1"},
            {"BuildingCommandStateVar", "Page 1"},
            {"ChatSpeakerVar", "Page 1"},
            {"CinematicVar", "Page 1"},
            {"CivVar", "Page 1"},
            {"ColorVar", "Page 1"},
            {"CommandTypeVar", "Page 1"},
            {"ConceptVar", "Page 1"},
            {"ConceptListVar", "Page 1"},
            {"ControlTypeVar", "Page 1"},
            {"CostVar", "Page 1"},
            {"DataScalarVar", "Page 1"},
            {"DesignLineVar", "Page 1"},
            {"DesignLineListVar", "Page 1"},
            {"DifficultyVar", "Page 1"},
            {"DiplomacyVar", "Page 1"},
            {"EntityVar", "Page 1"},
            {"EntityFilterSetVar", "Page 1"},
            {"EventTypeVar", "Page 1"},
            {"ExposedScriptVar", "Page 1"},
            {"FlareTypeVar", "Page 1"},
            {"FlashableUIItemVar", "Page 1"},
            {"FloatVar", "Page 1"},
            {"FloatListVar", "Page 1"},
            {"GameStatePredicateVar", "Page 1"},
            {"GroupVar", "Page 1"},
            {"HUDItemVar", "Page 1"},
            {"IconTypeVar", "Page 2"},
            {"IntegerVar", "Page 2"},
            {"IntegerListVar", "Page 2"},
            {"IteratorVar", "Page 2"},
            {"KBBaseVar", "Page 2"},
            {"KBBaseListVar", "Page 2"},
            {"KBBaseQueryVar", "Page 2"},
            {"KBSquadFilterSetVar", "Page 2"},
            {"KBSquadListVar", "Page 2"},
            {"KBSquadQueryVar", "Page 2"},
            {"LeaderVar", "Page 2"},
            {"ListPositionVar", "Page 2"},
            {"LocationVar", "Page 2"},
            {"LocStringIDVar", "Page 2"},
            {"LOSTypeVar", "Page 2"},
            {"MathOperatorVar", "Page 2"},
            {"MessageIndexVar", "Page 2"},
            {"MessageJustifyVar", "Page 2"},
            {"MessagePointVar", "Page 2"},
            {"MissionStateVar", "Page 2"},
            {"MissionTargetTypeVar", "Page 2"},
            {"MissionTypeVar", "Page 2"},
            {"ObjectVar", "Page 2"},
            {"ObjectDataRelativeVar", "Page 2"},
            {"ObjectDataTypeVar", "Page 2"},
            {"ObjectiveVar", "Page 2"},
            {"ObjectListVar", "Page 2"},
            {"ObjectTypeVar", "Page 2"},
            {"ObjectTypeListVar", "Page 2"},
            {"OperatorVar", "Page 2"},
            {"PercentVar", "Page 2"},
            {"PlacementRuleVar", "Page 3"},
            {"PlayerVar", "Page 3"},
            {"PlayerListVar", "Page 3"},
            {"PlayerStateVar", "Page 3"},
            {"PowerVar", "Page 3"},
            {"ProtoObjectVar", "Page 3"},
            {"ProtoObjectListVar", "Page 3"},
            {"ProtoSquadVar", "Page 3"},
            {"ProtoSquadListVar", "Page 3"},
            {"RefCountTypeVar", "Page 3"},
            {"RumbleTypeVar", "Page 3"},
            {"SoundVar", "Page 3"},
            {"SquadVar", "Page 3"},
            {"SquadDataTypeVar", "Page 3"},
            {"SquadFlagVar", "Page 3"},
            {"SquadListVar", "Page 3"},
            {"SquadModeVar", "Page 3"},
            {"StringVar", "Page 3"},
            {"TalkingHeadVar", "Page 3"},
            {"TeamVar", "Page 3"},
            {"TeamListVar", "Page 3"},
            {"TechVar", "Page 3"},
            {"TechListVar", "Page 3"},
            {"TechStatusVar", "Page 3"},
            {"TimeVar", "Page 3"},
            {"UIButtonVar", "Page 3"},
            {"UILocationVar", "Page 3"},
            {"UILocationMinigameVar", "Page 3"},
            {"UISquadVar", "Page 3"},
            {"UISquadListVar", "Page 3"},
            {"UnitVar", "Page 4"},
            {"UnitFlagVar", "Page 4"},
            {"UnitListVar", "Page 4"},
            {"UserClassTypeVar", "Page 4"},
            {"VectorVar", "Page 4"},
            {"VectorListVar", "Page 4"},
            {"AIAnalyzeKBSquadList", "AI"},
            {"AIAnalyzeOffenseAToB", "AI"},
            {"AIAnalyzeProtoSquadList", "AI"},
            {"AIAnalyzeSquadList", "AI"},
            {"AIBindLog", "AI"},
            {"AICalculateOffenseRatioAToB", "AI"},
            {"AIClearOpportunityRequests", "AI"},
            {"AICreateAreaTarget", "AI"},
            {"AICreateTargetWrapper", "AI"},
            {"AIDeleteCTFMission", "AI|Mission"},
            {"AIFactoidSubmit", "AI"},
            {"AIGetAlertData", "AI"},
            {"AIGetAttackAlerts", "AI"},
            {"AIGetFlareAlerts", "AI"},
            {"AIGetLastAttackAlert", "AI"},
            {"AIGetLastFlareAlert", "AI"},
            {"AIGetMemory", "AI"},
            {"AIGetMissions", "AI|Mission"},
            {"AIGetMissionTargets", "AI|Mission"},
            {"AIGetTerminalMissions", "AI|Mission"},
            {"AIMissionAddSquads", "AI|Mission"},
            {"AIMissionCancel", "AI|Mission"},
            {"AIMissionCreate", "AI|Mission"},
            {"AIMissionGetLaunchScores", "AI|Mission"},
            {"AIMissionGetTarget", "AI|Mission"},
            {"AIMissionGetValidSquads", "AI|Mission"},
            {"AIMissionRemoveSquads", "AI|Mission"},
            {"AIMissionSetFlags", "AI|Mission"},
            {"AIMissionSetMoveAttack", "AI|Mission"},
            {"AIMissionSetTargetInfo", "AI|Mission"},
            {"AIMissionTargetGetLocation", "AI|Mission"},
            {"AIMissionTargetGetScores", "AI|Mission"},
            {"AIQueryMissionTargets", "AI|Mission"},
            {"AIRegisterHook", "AI"},
            {"AIRemoveFromMissions", "AI|Mission"},
            {"AISAGetComponent", "AI"},
            {"AIScoreMissionTargets", "AI|Mission"},
            {"AISetAssetMultipliers", "AI|Set"},
            {"AISetBiases", "AI|Set"},
            {"AISetFocus", "AI|Set"},
            {"AISetPlayerAssetModifier", "AI|Set"},
            {"AISetPlayerBuildSpeedModifiers", "AI|Set"},
            {"AISetPlayerDamageModifiers", "AI|Set"},
            {"AISetPlayerMultipliers", "AI|Set"},
            {"AISetScoringParms", "AI|Set"},
            {"AISortMissionTargets", "AI|Mission"},
            {"AITopicCreate", "AI"},
            {"AITopicLotto", "AI"},
            {"AITopicModifyTickets", "AI"},
            {"AITopicPriorityRequest", "AI"},
            {"AIWrapperModifyFlags", "AI"},
            {"AIWrapperModifyParms", "AI"},
            {"AIWrapperModifyRadius", "AI"},
            {"AsFloat", "Math|Convert"},
            {"AsInt", "Math|Convert"},
            {"AsString", "Math|Convert"},
            {"AsTime", "Math|Convert"},
            {"AttachmentAddObject", "Game|Units|Attachment"},
            {"AttachmentAddType", "Game|Units|Attachment"},
            {"AttachmentRemoveAll", "Game|Units|Attachment"},
            {"AttachmentRemoveType", "Game|Units|Attachment"},
            {"BidAddToMissions", "Misc|Bid"},
            {"BidCreateBuilding", "Misc|Bid"},
            {"BidCreatePower", "Misc|Bid"},
            {"BidCreateSquad", "Misc|Bid"},
            {"BidCreateTech", "Misc|Bid"},
            {"BidDelete", "Misc|Bid"},
            {"BidGetData", "Misc|Bid"},
            {"BidPurchase", "Misc|Bid"},
            {"BidQuery", "Misc|Bid"},
            {"BidSetBlockedBuilders", "Misc|Bid"},
            {"BidSetQueueLimits", "Misc|Bid"},
            {"BlockLeaderPowers", "Game|Powers"},
            {"BlockMinimap", "Game|Player"},
            {"BuildingCommand", "Game|Create"},
            {"CalculatePercentTime", "Math"},
            {"CameraShake", "Game|Player"},
            {"ChangeOwner", "Game|Units"},
            {"ChangeSquadMode", "Game|Units"},
            {"ClearBuildingCommandState", "Game|Create"},
            {"ClearCorpseUnits", "Game|World"},
            {"Cloak", "Game|Units"},
            {"CloakDetected", "Game|Units"},
            {"CombatDamage", "Game|Units"},
            {"ConceptGetParameters", "Misc|Concept"},
            {"ConceptPermission", "Misc|Concept"},
            {"ConceptResetCooldown", "Misc|Concept"},
            {"ConceptSetParameters", "Misc|Concept"},
            {"ConceptSetPrecondition", "Misc|Concept"},
            {"ConceptSetState", "Misc|Concept"},
            {"ConceptStartSub", "Misc|Concept"},
            {"ConvertKBSquadsToSquads", "Math|Convert"},
            {"CopyAISquadAnalysis", "Copy"},
            {"CopyBool", "Copy"},
            {"CopyChatSpeaker", "Copy"},
            {"CopyColor", "Copy"},
            {"CopyCost", "Game|Player|Cost"},
            {"CopyCount", "Copy"},
            {"CopyDesignLine", "Copy"},
            {"CopyDesignLineList", "Copy"},
            {"CopyDirection", "Copy"},
            {"CopyDistance", "Copy"},
            {"CopyFloat", "Copy"},
            {"CopyFloatList", "Copy"},
            {"CopyInt", "Copy"},
            {"CopyIntegerList", "Copy"},
            {"CopyKBBase", "Copy"},
            {"CopyLocation", "Copy"},
            {"CopyLocationList", "Copy"},
            {"CopyLocStringID", "Copy"},
            {"CopyObjective", "Copy"},
            {"CopyObjectList", "Copy"},
            {"CopyObjectType", "Copy"},
            {"CopyObjectTypeList", "Copy"},
            {"CopyPercent", "Copy"},
            {"CopyPlayer", "Copy"},
            {"CopyProtoObject", "Copy"},
            {"CopyProtoObjectList", "Copy"},
            {"CopyProtoSquad", "Copy"},
            {"CopyProtoSquadList", "Copy"},
            {"CopySound", "Copy"},
            {"CopySquad", "Copy"},
            {"CopySquadList", "Copy"},
            {"CopyString", "Copy"},
            {"CopyTech", "Copy"},
            {"CopyTechList", "Copy"},
            {"CopyTime", "Copy"},
            {"CopyUnit", "Copy"},
            {"CopyUnitList", "Copy"},
            {"CostToFloat", "Game|Player|Cost"},
            {"CountIncrement", "Math"},
            {"CreateIconObject", "Game|Create"},
            {"CreateObject", "Game|Create"},
            {"CreateObstructionUnit", "Game|Create"},
            {"CreateSquad", "Game|Create"},
            {"CreateSquads", "Game|Create"},
            {"CreateUnit", "Game|Create"},
            {"CustomCommandAdd", "Game|Units"},
            {"CustomCommandExecute", "Game|Units"},
            {"CustomCommandRemove", "Game|Units"},
            {"Damage", "Game|Units"},
            {"DesignLineGetPoints", "Misc|Design"},
            {"DesignLineListAdd", "Misc|Design"},
            {"DesignLineListGetSize", "Misc|Design"},
            {"DesignLineListRemove", "Misc|Design"},
            {"Destroy", "Game|Units"},
            {"EnableChats", "Game|UI/Input"},
            {"EnableFogOfWar", "Game|World"},
            {"EnableMusicManager", "Game|Audio"},
            {"EventClearFilters", "Misc|Event"},
            {"EventFilterCamera", "Misc|Event"},
            {"EventFilterEntity", "Misc|Event"},
            {"EventFilterGameState", "Misc|Event"},
            {"EventFilterNumeric", "Misc|Event"},
            {"EventReset", "Misc|Event"},
            {"EventSubscribe", "Misc|Event"},
            {"EventSubscribeUseCount", "Misc|Event"},
            {"FadeTransition", "Game|UI/Input"},
            {"FilterAddCanChangeOwner", "Misc|Filter"},
            {"FilterAddDiplomacy", "Misc|Filter"},
            {"FilterAddIsAlive", "Misc|Filter"},
            {"FilterAddIsIdle", "Misc|Filter"},
            {"FilterAddIsSelected", "Misc|Filter"},
            {"FilterAddJacking", "Misc|Filter"},
            {"FilterAddMaxObjectType", "Misc|Filter"},
            {"FilterAddObjectTypes", "Misc|Filter"},
            {"FilterAddPlayers", "Misc|Filter"},
            {"FilterAddProtoObjects", "Misc|Filter"},
            {"FilterAddProtoSquads", "Misc|Filter"},
            {"FilterAddRefCount", "Misc|Filter"},
            {"FilterAddTeams", "Misc|Filter"},
            {"FilterClear", "Misc|Filter"},
            {"FlareMinimapNormal", "Game|UI/Input"},
            {"FlareMinimapSpoof", "Game|UI/Input"},
            {"FlashEntity", "Game|Units|Visual"},
            {"FlashUIElement", "Game|UI/Input"},
            {"FloatListAdd", "Lists|Float"},
            {"FloatListRemove", "Lists|Float"},
            {"Forbid", "Game|Player"},
            {"GetChildUnits", "Game|Units|Get"},
            {"GetClosestPowerSquad", "Game|Units|Get"},
            {"GetClosestSquad", "Game|Units|Get"},
            {"GetClosestUnit", "Game|Units|Get"},
            {"GetCost", "Game|Player|Cost"},
            {"GetCTFFlag", "Game|Scenario|DLC"},
            {"GetCTFFlagCarrier", "Game|Scenario|DLC"},
            {"GetDifficulty", "Game|Player"},
            {"GetDirection", "Game|World"},
            {"GetDirectionFromLocations", "Game|World"},
            {"GetDistanceLocationLocation", "Game|World"},
            {"GetDistanceUnitLocation", "Game|World"},
            {"GetDLCGameMode", "Game|Scenario|DLC"},
            {"GetGameMode", "Game|Scenario|DLC"},
            {"GetGameTime", "Game|Time"},
            {"GetGarrisonedSquads", "Game|Units|Get"},
            {"GetGarrisonedUnits", "Game|Units|Get"},
            {"GetHealth", "Game|Units|Get"},
            {"GetIdleDuration", "Game|Units|Get"},
            {"GetKBBaseLocation", "Game|World"},
            {"GetLegalBuildings", "Game|Player"},
            {"GetLegalSquads", "Game|Player"},
            {"GetLegalTechs", "Game|Player"},
            {"GetLocation", "Game|Units|Get"},
            {"GetMeanLocation", "Game|World"},
            {"GetNPCPlayersByName", "Game|Player"},
            {"GetNumTransports", "Game|Units|Get"},
            {"GetObstructionRadius", "Game|World"},
            {"GetOwner", "Game|Units|Get"},
            {"GetParentSquad", "Game|Units|Get"},
            {"GetPlayerCiv", "Game|Player"},
            {"GetPlayerEconomy", "Game|Player"},
            {"GetPlayerLeader", "Game|Player"},
            {"GetPlayerPop", "Game|Player"},
            {"GetPlayers", "Game|Player"},
            {"GetPlayers2", "Game|Player"},
            {"GetPlayerScore", "Game|Player"},
            {"GetPlayerTeam", "Game|Player"},
            {"GetPop", "Game|Player"},
            {"GetPopularSquadType", "Game|Units|Get"},
            {"GetPowerRadius", "Game|Powers"},
            {"GetProtoObject", "Game|Units|Get"},
            {"GetProtoSquad", "Game|Units|Get"},
            {"GetResources", "Game|Player"},
            {"GetSquads", "Game|Player"},
            {"GetSquadTrainerType", "Game|Units|Get"},
            {"GetTeamPlayers", "Game|Team"},
            {"GetTeams", "Game|Team"},
            {"GetTechResearcherType", "Game|Player"},
            {"GetUnits", "Game|Player"},
            {"GetUTechBldings", "Game|Player"},
            {"GrantAchievement", "Game|Player"},
            {"GrantAchievementToPlayer", "Game|Player"},
            {"HintCalloutCreate", "Game|Hints"},
            {"HintCalloutDestroy", "Game|Hints"},
            {"HintGlowToggle", "Game|Hints"},
            {"HintMessageDestroy", "Game|Hints"},
            {"HintMessageShow", "Game|Hints"},
            {"HUDToggle", "Game|UI/Input"},
            {"IgnoreDpad", "Game|UI/Input"},
            {"Infect", "Game|Units"},
            {"InputUIButton", "Game|UI/Input"},
            {"InputUILocation", "Game|UI/Input"},
            {"InputUILocationMinigame", "Game|UI/Input"},
            {"InputUIPlaceSquads", "Game|UI/Input"},
            {"InputUISquad", "Game|UI/Input"},
            {"InputUISquadList", "Game|UI/Input"},
            {"IntDecrement", "Math"},
            {"IntegerListAdd", "Lists|Int"},
            {"IntegerListGetSize", "Lists|Int"},
            {"IntegerListRemove", "Lists|Int"},
            {"IntIncrement", "Math"},
            {"IntToCount", "Math|Convert"},
            {"InvertBool", "Math|Convert"},
            {"IteratorKBBaseList", "Misc|KB"},
            {"IteratorLocationList", "Lists|Location"},
            {"IteratorPlayerList", "Lists|Player"},
            {"IteratorProtoSquadList", "Lists|Proto"},
            {"IteratorSquadList", "Lists|Squad"},
            {"IteratorTeamList", "Lists|Team"},
            {"IteratorUnitList", "Lists|Unit"},
            {"KBAddSquadsToKB", "Misc|KB"},
            {"KBBaseGetMass", "Misc|KB"},
            {"KBBQExecute", "Misc|KB"},
            {"KBBQExecuteClosest", "Misc|KB"},
            {"KBBQPlayerRelation", "Misc|KB"},
            {"KBSFAddObjectTypes", "Misc|KB"},
            {"KBSQExecute", "Misc|KB"},
            {"KBSQInit", "Misc|KB"},
            {"KBSQObjectType", "Misc|KB"},
            {"KBSQPlayerRelation", "Misc|KB"},
            {"KBSquadListFilter", "Misc|KB"},
            {"Kill", "Game|Units"},
            {"KillUnits", "Game|Units"},
            {"LaunchCinematic", "Game|UI/Input"},
            {"LaunchProjectile", "Game|World"},
            {"LaunchScript", "Special"},
            {"TriggerActivate", "Special"},
            {"TriggerDeactivate", "Special"},
            {"Shutdown", "Special"},
            {"ClearBlackMap", "Misc"},
            {"ResetBlackMap", "Misc"},
            {"LerpInt", "Math"},
            {"LerpLocation", "Math"},
            {"LerpPercent", "Math"},
            {"LerpTime", "Math"},
            {"LocationAdjust", "Game|World"},
            {"LocationAdjustDir", "Game|World"},
            {"LocationListAdd", "Lists|Location"},
            {"LocationListGetByIndex", "Lists|Location"},
            {"LocationListGetClosest", "Lists|Location"},
            {"LocationListGetSize", "Lists|Location"},
            {"LocationListPartition", "Lists|Location"},
            {"LocationListRemove", "Lists|Location"},
            {"LocationListShuffle", "Lists|Location"},
            {"LocationTieToGround", "Game|World"},
            {"MathFloat", "Math"},
            {"MathHitpoints", "Math"},
            {"MathInt", "Math"},
            {"MathLocation", "Math"},
            {"MathPercent", "Math"},
            {"MathResources", "Math"},
            {"MathTime", "Math"},
            {"MegaTurretAttack", "Game|World"},
            {"MissionResult", "Game|Scenario"},
            {"ModifyDataScalar", "Math"},
            {"ModifyProtoData", "Game|Player"},
            {"ModifyProtoSquadData", "Game|Player"},
            {"Move", "Game|Units"},
            {"MovePath", "Game|Units"},
            {"ObjectiveComplete", "Game|Scenario"},
            {"ObjectiveDecrementCounter", "Game|Scenario"},
            {"ObjectiveDisplay", "Game|Scenario"},
            {"ObjectiveGetFinalCounter", "Game|Scenario"},
            {"ObjectiveIncrementCounter", "Game|Scenario"},
            {"ObjectListRemove", "Lists|Object"},
            {"ObjectTypeToProtoObjects", "Math|Convert"},
            {"PatherObstructionRebuild", "Game|World"},
            {"PatherObstructionUpdates", "Game|World"},
            {"PayCost", "Game|Player|Cost"},
            {"PlayAnimationObject", "Game|Units|Visual"},
            {"PlayAnimationSquad", "Game|Units|Visual"},
            {"PlayAnimationUnit", "Game|Units|Visual"},
            {"PlayChat", "Game|UI/Input"},
            {"PlayerListAdd", "Lists|Player"},
            {"PlayerListGetSize", "Lists|Player"},
            {"PlayerListRemove", "Lists|Player"},
            {"PlayRelationSound", "Game|UI/Input"},
            {"PlaySound", "Game|UI/Input"},
            {"PlaySoundFile", "Game|UI/Input"},
            {"PlayWorldSoundOnEntity", "Game|UI/Input"},
            {"PowerChargeUseOf", "Game|Powers"},
            {"PowerClear", "Game|Powers"},
            {"PowerGrant", "Game|Powers"},
            {"PowerInvoke", "Game|Powers"},
            {"PowerMenuEnable", "Game|Powers"},
            {"PowerRevoke", "Game|Powers"},
            {"PowerUserShutdown", "Game|Powers"},
            {"ProtoObjectListAdd", "Lists|Proto"},
            {"ProtoObjectListRemove", "Lists|Proto"},
            {"ProtoObjectListShuffle", "Lists|Proto"},
            {"ProtoSquadListAdd", "Lists|Proto"},
            {"ProtoSquadListGetSize", "Lists|Proto"},
            {"ProtoSquadListRemove", "Lists|Proto"},
            {"ProtoSquadListShuffle", "Lists|Proto"},
            {"RallyPointGet", "Game|Player"},
            {"RallyPointSet", "Game|Player"},
            {"RandomCount", "Math"},
            {"RandomInt", "Math"},
            {"RandomLocation", "Math"},
            {"RandomTime", "Math"},
            {"RecycleBuilding", "Game|Units"},
            {"RefCountSquadAdd", "Misc|Ref"},
            {"RefCountSquadRemove", "Misc|Ref"},
            {"RefCountUnitAdd", "Misc|Ref"},
            {"RefCountUnitRemove", "Misc|Ref"},
            {"RefundCost", "Game|Player|Cost"},
            {"Repair", "Game|Units"},
            {"RepairByCombatValue", "Game|Units"},
            {"ResetAbilityTimer", "Game|Units"},
            {"ResetDopple", "Game|Units"},
            {"Revealer", "Game|World"},
            {"RumbleStart", "Game|UI/Input"},
            {"SetAutoAttackable", "Game|Units|Set"},
            {"SetCamera", "Game|Player"},
            {"setCTFCount", "Game|Scenario|DLC"},
            {"SetCTFFlag", "Game|Scenario|DLC"},
            {"ClearCTFFlagOrCarrier", "Game|Scenario|DLC"},
            {"SetDirection", "Game|World"},
            {"SetGarrisonedCount", "Game|Units|Set"},
            {"SetIgnoreUserInput", "Game|UI/Input"},
            {"SetLevel", "Game|Units|Set"},
            {"SetMinimapNorthPointerRotation", "Game|UI/Input"},
            {"SetMinimapSkirtMirroring", "Game|UI/Input"},
            {"SetMobile", "Game|Units|Set"},
            {"SetOverrideTint", "Game|Units|Visual"},
            {"SetPlayableBounds", "Game|World"},
            {"SetPlayerPop", "Game|Player"},
            {"SetPlayerState", "Game|Player"},
            {"SetPosition", "Game|World"},
            {"SetRenderTerrainSkirt", "Game|World"},
            {"SetResourceHandicap", "Game|Player"},
            {"SetResources", "Game|Player"},
            {"SetScenarioScoreInfo", "Game|Scenario"},
            {"SetSelectable", "Game|Units|Set"},
            {"SetTeleporterDestination", "Game|Units|Set"},
            {"Settle", "Game|Units"},
            {"SetTowerWallDestination", "Misc"},
            {"SetTransportPickUpLocations", "Game|Units|Set"},
            {"SetTrickleRate", "Game|Player"},
            {"SetUIPowerRadius", "Game|UI/Input"},
            {"SetUnitAttackTarget", "Game|Units|Set"},
            {"ShowMessage", "Game|UI/Input"},
            {"ShowObjectivePointer", "Game|UI/Input"},
            {"SquadFlagSet", "Game|Units"},
            {"SquadListAdd", "Lists|Squad"},
            {"SquadListDiff", "Lists|Squad"},
            {"SquadListFilter", "Lists|Squad"},
            {"SquadListGetSize", "Lists|Squad"},
            {"SquadListPartition", "Lists|Squad"},
            {"SquadListRemove", "Lists|Squad"},
            {"SquadListShuffle", "Lists|Squad"},
            {"TableLoad", "Game|UI/Input"},
            {"TeamListAdd", "Lists|Team"},
            {"TeamListRemove", "Lists|Team"},
            {"TeamSetDiplomacy", "Game|Team"},
            {"TeamsToPlayers", "Game|Team"},
            {"TechActivate", "Game|Player"},
            {"TechDeactivate", "Game|Player"},
            {"TechListAdd", "Lists|Tech"},
            {"TechListRemove", "Lists|Tech"},
            {"Teleport", "Game|Units"},
            {"TeleportUnitsOffObstruction", "Game|Units"},
            {"TimerCreate", "Game|Time"},
            {"TimerDestroy", "Game|Time"},
            {"TimerGet", "Game|Time"},
            {"TimerSet", "Game|Time"},
            {"TimerSetPaused", "Game|Time"},
            {"TimeToFloat", "Math|Convert"},
            {"TowSetScore", "Game|Scenario|DLC"},
            {"TowSetVisible", "Game|Scenario|DLC"},
            {"TransferGarrisoned", "Game|Units"},
            {"Transform", "Game|World"},
            {"TransportSquads", "Game|Units"},
            {"TugOfWarMarkPlayersAsTrailing", "Game|Scenario|DLC"},
            {"UITogglePowerOverlay", "Game|UI/Input"},
            {"UIUnlock", "Game|UI/Input"},
            {"UnitFlagSet", "Game|Units"},
            {"UnitListAdd", "Lists|Unit"},
            {"UnitListDiff", "Lists|Unit"},
            {"UnitListFilter", "Lists|Unit"},
            {"UnitListGetSize", "Lists|Unit"},
            {"UnitListPartition", "Lists|Unit"},
            {"UnitListRemove", "Lists|Unit"},
            {"UnitListShuffle", "Lists|Unit"},
            {"Unload", "Game|Units"},
            {"UsePower", "Game|Powers"},
            {"UserMessage", "Game|UI/Input"},
            {"Work", "Game|Units"},
            {"AICanGetDifficultySetting", "AI"},
            {"AITopicGetTickets", "AI"},
            {"AITopicIsActive", "AI"},
            {"ASYNCPlayerSelectingSquad", "Game|Player"},
            {"ASYNCUnitsOnScreenSelected", "Game|Units"},
            {"BidState", "Misc|Bid"},
            {"BuildingCommandDone", "Game|Create"},
            {"CanGetBuilder", "CanGet"},
            {"CanGetCentroid", "CanGet"},
            {"CanGetCoopPlayer", "CanGet"},
            {"CanGetCorpseUnits", "CanGet"},
            {"CanGetCTFMissionTarget", "CanGet"},
            {"CanGetDesignSpheres", "CanGet"},
            {"CanGetGreatestThreat", "CanGet"},
            {"CanGetHoverPoint", "CanGet"},
            {"CanGetOneDesignLine", "CanGet"},
            {"CanGetOneFloat", "CanGet"},
            {"CanGetOneInteger", "CanGet"},
            {"CanGetOneLocation", "CanGet"},
            {"CanGetOneObject", "CanGet"},
            {"CanGetOnePlayer", "CanGet"},
            {"CanGetOneProtoObject", "CanGet"},
            {"CanGetOneProtoSquad", "CanGet"},
            {"CanGetOneSocketUnit", "CanGet"},
            {"CanGetOneSquad", "CanGet"},
            {"CanGetOneTeam", "CanGet"},
            {"CanGetOneTech", "CanGet"},
            {"CanGetOneUnit", "CanGet"},
            {"CanGetRandomLocation", "CanGet"},
            {"CanGetSocketParentBuilding", "CanGet"},
            {"CanGetSocketPlugUnit", "CanGet"},
            {"CanGetSocketUnits", "CanGet"},
            {"CanGetSquads", "CanGet"},
            {"CanGetUnitLaunchLocation", "CanGet"},
            {"CanGetUnits", "CanGet"},
            {"CanGetUnitsAlongRay", "CanGet"},
            {"CanPayCost", "Game|Player|Cost"},
            {"CanRemoveOneFloat", "Lists|Float"},
            {"CanRemoveOneInteger", "Lists|Int"},
            {"CanRemoveOneLocation", "Lists|Location"},
            {"CanRemoveOneProtoObject", "Lists|Proto"},
            {"CanRemoveOneProtoSquad", "Lists|Proto"},
            {"CanRemoveOneTech", "Lists|Tech"},
            {"CanRetrieveExternalFloat", "Setup"},
            {"CanRetrieveExternalLocation", "Setup"},
            {"CanRetrieveExternalLocationList", "Setup"},
            {"CanRetrieveExternals", "Setup"},
            {"CanUsePower", "Game|Powers"},
            {"ChatCompleted", "Game|UI/Input"},
            {"CheckAndSetFalse", "Misc"},
            {"CheckDifficulty", "Game"},
            {"CheckDiplomacy", "Game"},
            {"CheckModeChange", "Game|Units"},
            {"CheckPlacement", "Game|World"},
            {"CheckPop", "Game|Player"},
            {"CheckResourcesTotals", "Game|Player"},
            {"CinematicCompleted", "Game|UI/Input"},
            {"CompareAIMissionState", "Compare"},
            {"CompareAIMissionType", "Compare"},
            {"CompareBool", "Compare"},
            {"CompareCiv", "Compare"},
            {"CompareCount", "Compare"},
            {"CompareDesignLine", "Compare"},
            {"CompareFloat", "Compare"},
            {"CompareHitpoints", "Compare"},
            {"CompareInteger", "Compare"},
            {"CompareLeader", "Compare"},
            {"CompareLocStringID", "Compare"},
            {"ComparePercent", "Compare"},
            {"ComparePlayers", "Compare"},
            {"ComparePlayerSquadCount", "Compare"},
            {"ComparePlayerUnitCount", "Compare"},
            {"CompareProtoObject", "Compare"},
            {"CompareProtoSquad", "Compare"},
            {"CompareString", "Compare"},
            {"CompareTeams", "Compare"},
            {"CompareTech", "Compare"},
            {"CompareTime", "Compare"},
            {"CompareUnit", "Compare"},
            {"CompareVector", "Compare"},
            {"ConceptGetCommand", "Misc|Concept"},
            {"ConceptGetStateChange", "Misc|Concept"},
            {"ContainsGarrisoned", "Contains"},
            {"CustomCommandCheck", "Game|Units"},
            {"EventTriggered", "Misc|Event"},
            {"FadeCompleted", "Game|UI/Input"},
            {"GameTime", "Game"},
            {"GameTimeReached", "Game"},
            {"GetTableRow", "CustomData"},
            {"HasGarrisoned", "Game"},
            {"IsAlive", "Game|Units"},
            {"IsAttached", "Game|Units"},
            {"IsAttacking", "Game|Units"},
            {"IsBuilt", "Game|Units"},
            {"IsCapturing", "Game|Units"},
            {"IsConfigDefined", "Misc"},
            {"IsCoop", "Game"},
            {"IsDead", "Game|Units"},
            {"IsEmptySocketUnit", "Game|Units"},
            {"IsForbidden", "Game"},
            {"IsGarrisoned", "Game|Units"},
            {"IsGathering", "Game|Units"},
            {"IsHitched", "Game|Units"},
            {"IsIdle", "Game|Units"},
            {"IsMap", "Game"},
            {"IsMoving", "Game|Units"},
            {"IsObjectType", "Game"},
            {"IsOwnedBy", "Game"},
            {"IsProtoObject", "Game"},
            {"IsSelectable", "Game|Units"},
            {"IsUnderAttack", "Game|Units"},
            {"MarkerSquadsInArea", "Game"},
            {"NextKBBase", "Iterator"},
            {"NextLocation", "Iterator"},
            {"NextPlayer", "Iterator"},
            {"NextProtoSquad", "Iterator"},
            {"NextSquad", "Iterator"},
            {"NextTeam", "Iterator"},
            {"NextUnit", "Iterator"},
            {"PlayerInState", "Game"},
            {"PlayerIsComputerAI", "Game|Player"},
            {"PlayerIsHuman", "Game|Player"},
            {"PlayerUsingLeader", "Game|Player"},
            {"ProtoObjectListContains", "Lists|Proto"},
            {"ProtoSquadListContains", "Lists|Proto"},
            {"RefCountSquad", "Misc|Ref"},
            {"RefCountUnit", "Misc|Ref"},
            {"SquadLocationDistance", "Game|World"},
            {"TechListContains", "Lists|Tech"},
            {"TechStatus", "Game"},
            {"TimerIsDone", "Game"},
            {"TriggerActiveTime", "Setup"},
            {"UIButtonPressed", "Game|UI/Input"},
            {"UILocationCancel", "Game|UI/Input"},
            {"UILocationMinigameCancel", "Game|UI/Input"},
            {"UILocationMinigameOK", "Game|UI/Input"},
            {"UILocationMinigameUILockError", "Game|UI/Input"},
            {"UILocationMinigameWaiting", "Game|UI/Input"},
            {"UILocationOK", "Game|UI/Input"},
            {"UILocationUILockError", "Game|UI/Input"},
            {"UILocationWaiting", "Game|UI/Input"},
            {"UISquadCancel", "Game|UI/Input"},
            {"UISquadListCancel", "Game|UI/Input"},
            {"UISquadListOK", "Game|UI/Input"},
            {"UISquadListUILockError", "Game|UI/Input"},
            {"UISquadListWaiting", "Game|UI/Input"},
            {"UISquadOK", "Game|UI/Input"},
            {"UISquadUILockError", "Game|UI/Input"},
            {"UISquadWaiting", "Game|UI/Input"},
            {"UnitLocationDistance", "Game|World"},
            {"UnitUnitDistance", "Game|World"}
};

foreach (string file in new string[] { "E:\\Repos\\Foundry\\Foundry.Core\\HW1\\Script\\conditions.tsdef", "E:\\Repos\\Foundry\\Foundry.Core\\HW1\\Script\\effects.tsdef" })
{
    XDocument doc = XDocument.Load(file);

    foreach (var n in doc.Root.Elements())
    {
        if (n.Name == "Logic")
        {
            string val = "";
            if (categories.ContainsKey(n.Attribute("Name").Value))
            {
                val = categories[n.Attribute("Name").Value];
            }
            else
            {
                Console.WriteLine(n.Attribute("Name"));
                val = Console.ReadLine();
            }
            n.SetAttributeValue("Category", val);
        }
    }

    doc.Save(file);
}